### 익명 회원가입
POST {{api}}/api/v1/auth/anonymous
Content-Type: application/json

> {%
client.global.set("SESSION_ID", response.body["token"])
%}


### 카카오 로그인
POST {{api}}/api/v1/auth
Content-Type: application/json

{
    "code": "n-oYeqg0bfTl8HKhGGgEKBMQ7UCd8i75Tqj1I3To_V0pFBO-idJ_DYkmC0Hnh4MdyhHXpgopcNEAAAGCulyZqQ",
    "redirectUri": "http://localhost:3000/auth/kakao/callback",
    "socialType": "KAKAO"
}

> {%
client.global.set("SESSION_ID", response.body["token"])
%}


### 로그아웃
POST {{api}}/api/v1/logout
Content-Type: application/json
Authorization: Bearer {{SESSION_ID}}
