### 방을 생성합니다
POST {{api}}/api/v1/rooms
Content-Type: application/json
Authorization: Bearer {{SESSION_ID}}

{
    "description": "메쇼~쉬는탐"
}

> {%
client.global.set("ROOM_ID", response.body["roomId"])
%}


### 방에 대한 정보를 수정합니다
PUT {{api}}/api/v1/rooms/{{ROOM_ID}}
Content-Type: application/json
Authorization: Bearer {{SESSION_ID}}

{
    "description": "메쇼~쉬는탐",
    "moods": [
        "분위기 좋은",
        "신나는3",
        "여행3"
    ]
}


### 방을 삭제한다
DELETE {{api}}/api/v1/rooms/{{ROOM_ID}}
Authorization: Bearer {{SESSION_ID}}


### 내가 생성한 방을 조회합니다
GET {{api}}/api/v1/rooms
Authorization: Bearer {{SESSION_ID}}


> {%
client.global.set("INVITATION_KEY", response.body[0]["invitationKey"])
%}


### 방 초대장 정보를 조회합니다
GET {{api}}/api/v1/rooms/invitation/{{INVITATION_KEY}}
Authorization: Bearer {{SESSION_ID}}


### 초대장으로 방에 접속한다
PUT {{api}}/api/v1/rooms/invitation/{{INVITATION_KEY}}
Authorization: Bearer {{SESSION_ID}}
