### 나의 회원 정보를 조회합니다
GET {{api}}/api/v1/accounts
Authorization: Bearer token


### 나의 회원 정보를 조회합니다
PUT {{api}}/api/v1/accounts
Content-Type: application/json
Authorization: Bearer token

{
    "nickname": "새로운 닉네임",
    "profileUrl": "https://profile-image.png"
}
